# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Issues Month Statistics'
description: 'Create a issue to show month statistics by GitHub Actions'
author: 'xrkffgg'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  count-lables:
    description: 'For month-statistics'
  count-comments:
    description: 'For month-statistics'
  emoji:
    description: 'issue emoji'
  labels:
    description: 'labels'
  assignees:
    description: 'assignees'

#outputs:
#  result:
#    description: action result

runs:
  using: 'node12'
  main: 'dist/index.js'
